### ISSUE TITLE
TEST: Is apikey private?

### ISSUE THREAD

**Issue by maormagori** [maormagori/EPUBCLOUD-cli#10]
Is the apikey flag necessary?
Still not sure.
It's either account-specific or client-specific. Some testing is needed to make sure I won't publish anything private.

**Comment by matanmi12** [comment]
but how do you get the api key within the app?

**Comment by maormagori** [comment]
@matanmi12 
I used a MITM to sniff hbreader app's requests and each request contained the API key.
That won't be necessary for you to do though, I just need to open a new account and check whether the keys are different. I just haven't gotten to it yet.

**Comment by maormagori** [comment]
After some testing it seems that the API key is platform-specific, It probably helps with statistics.
I'll make a PR adding the key as a const and remove the flag!

**Comment by matanmi12** [comment]
Great, let me know if I can help with testing

**Comment by maormagori** [comment]
@matanmi12 
It's great to see some activity around this project.
It was a weekend project for me and I left it as a work in progress but you're welcome to contribute and I'll try to help out as well. 
Please note though that I'm not using the EPUBCLOUD anymore so I won't be aware if this no longer works.

**Comment by matanmi12** [comment]
As of now, the new version is working well. Thanks!
